name: MoneyRankSystem
version: '${project.version}'
main: me.skythebuilder.moneyranksystem.TierListPlugin
api-version: '1.20'

depend:
  - Vault
  - PlaceholderAPI

commands:
  checkmoney:
    description: Check the money and rank of a player.
    usage: /checkmoney [player]
  moneyreload:
    description: Reload the TierList config.
    usage: /moneyreload

permissions:
  tierlist.reload:
    description: Allows the player to reload the TierList config.
    default: op